# Generated by Django 5.2.12 on 2026-04-09 18:44

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('age', models.DateField()),
                ('gender', models.CharField(choices=[('boy', 'Хлопчик'), ('girl', 'Дівчинка')], max_length=25)),
                ('size', models.CharField(choices=[('small', 'Малий (до 30 см)'), ('medium', 'Середній (30-50 см)'), ('large', 'Великий (50+ см)')], max_length=25)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('is_adopted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animals.animaltype')),
                ('characters', models.ManyToManyField(to='animals.character')),
            ],
        ),
    ]
