# Generated by Django 5.2.12 on 2026-05-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_adoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='status',
            field=models.CharField(choices=[('pending', 'Відправлена'), ('approved', 'Схвалена'), ('rejected', 'Відхилена')], default='pending', max_length=25),
        ),
    ]
