# Generated by Django 5.2.12 on 2026-05-02 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_adoption_status'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'animal_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
